name: Deploy Lambda Function
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function: ['lambda_function']
        deploy-group: ['dev_lambda']
        s3-key: ['appspec-$GITHUB_SHA']
        region: ['us-east-1']
        alias: ['pointer']
        appname: ['csye6225-lambda']
        deploy-config: ['CodeDeployDefault.LambdaAllAtOnce']
    steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        run: |
          sudo apt install -y curl
          sudo apt-get install -y unzip
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
      - name: Install jq
        run: |
          sudo apt-get install -y jq
      - name: Configure awscli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{matrix.region}}
      - name: Update lambda function and Push revision to S3
        run: |
          version1=`aws lambda get-alias --function-name ${{ matrix.function }} --name ${{ matrix.alias }} | jq '.FunctionVersion'`
          zip -r function.zip index.js
          version2=`aws lambda update-function-code \
                  --function-name ${{ matrix.function }} \
                  --zip-file fileb://function.zip \
                  --publish | jq .Version`
          echo "version before deploy: $version1"
          echo "version after deploy: $version2"   
          echo "{\"version\":0.0,\"Resources\":[{\"${{matrix.function}}\":{\"Type\":\"AWS::Lambda::Function\",\"Properties\":{\"Name\":\"${{matrix.function}}\",\"Alias\":\"${{matrix.alias}}\",\"CurrentVersion\":$version1,\"TargetVersion\":$version2}}}]}"> ${{matrix.s3-key}}.json
          aws s3 cp ${{matrix.s3-key}}.json s3://codedeploy.$account.trivedhaudurthi.me
        env:
          account: ${{secrets.ACCOUNT}}
      - name: Deploy Lambda Function
        run: |
          aws deploy create-deployment \
          --application-name ${{matrix.appname}} \
          --deployment-group-name ${{matrix.deploy-group}} \
          --deployment-config-name ${{matrix.deploy-config}} \
          --description "Deploy application revision ${{ matrix.s3-key }}" \
          --s3-location bucket=codedeploy.$account.trivedhaudurthi.me,bundleType=JSON,key=${{matrix.s3-key}}.json
        env:
          account: ${{secrets.ACCOUNT}}
